name = "mdbd"
main = "src/index.js"
compatibility_date = "2024-09-28"

[triggers]
crons = ["1 * * * *"] # Runs every hour at minute 1

[[kv_namespaces]]
binding = "MDBD"
id = "a070534470544fefa5f63fc2a485fb40"

[[d1_databases]]
binding = "D1_DB"
database_id = "04f9b03a-1779-4391-b497-862ce5300313"
database_name = "mdbd"